name: Keepalive
on:
  schedule:
    # Run every day at 1:01AM.
    # @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "1 1 * * *"

jobs:
  cronjob-based-github-action:
    name: Keep repo active for cron support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/keepalive-workflow
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.0.9
