name: Build Lucee Release

on:
  # Enable manual workflow runs
  workflow_dispatch:
  # Enable triggering a build via the github API
  # Or trigger a build from another repo via https://github.com/marketplace/actions/repository-dispatch
  repository_dispatch:
    types: [ forgebox_deploy ]

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    container: ghcr.io/foundeo/cfml-ci-tools/cfml-ci-tools:1.0.6
    if: ${{ github.ref }} == 'master'
    env:
      FORGEBOX_TOKEN: ${{ secrets.FORGEBOX_API_TOKEN }}
      S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      S3_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: box install --production

      - name: Fetch and publish Lucee releases
        run: box task run